/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DB.SQLiteConnection;
import java.io.File;
import javax.swing.JOptionPane;
import reto4.CuerpoDeAgua;

/**
 *
 * @author Esteban
 */
public class Screen extends javax.swing.JFrame {
    SQLiteConnection baseDeDatos = new SQLiteConnection("src/DB/cuerpos_de_agua.db");
    String arrayDB[][];
    String id;
    
    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_name = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        txt_city = new javax.swing.JTextField();
        lbl_city = new javax.swing.JLabel();
        txt_water_type = new javax.swing.JTextField();
        lbl_water_type = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        txt_body_type = new javax.swing.JTextField();
        lbl_body_type = new javax.swing.JLabel();
        txt_risk = new javax.swing.JTextField();
        lbl_risk = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarEnBD = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnProcess = new javax.swing.JButton();
        lbl_inputs = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_inputs = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_outputs = new javax.swing.JTextArea();
        lbl_outputs = new javax.swing.JLabel();
        btnGetData = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_name1 = new javax.swing.JTextField();
        lbl_name1 = new javax.swing.JLabel();
        txt_city1 = new javax.swing.JTextField();
        lbl_city1 = new javax.swing.JLabel();
        txt_water_type1 = new javax.swing.JTextField();
        lbl_water_type1 = new javax.swing.JLabel();
        txt_id1 = new javax.swing.JTextField();
        lbl_id1 = new javax.swing.JLabel();
        txt_body_type1 = new javax.swing.JTextField();
        lbl_body_type1 = new javax.swing.JLabel();
        txt_risk1 = new javax.swing.JTextField();
        lbl_risk1 = new javax.swing.JLabel();
        lbl_id2 = new javax.swing.JLabel();
        txt_id2 = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reto 4 Ciclo 2 Grupo NRC 1870");
        setResizable(false);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(418, 600));

        txt_name.setToolTipText("");
        txt_name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        lbl_name.setText("Nombre");

        txt_city.setToolTipText("");
        txt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cityActionPerformed(evt);
            }
        });

        lbl_city.setText("Municipio");

        txt_water_type.setToolTipText("");
        txt_water_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_water_typeActionPerformed(evt);
            }
        });

        lbl_water_type.setText("Tipo de agua");

        txt_id.setToolTipText("");
        txt_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_idFocusLost(evt);
            }
        });
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        lbl_id.setText("ID");

        txt_body_type.setToolTipText("");
        txt_body_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_body_typeActionPerformed(evt);
            }
        });

        lbl_body_type.setText("Tipo de cuerpo de agua");

        txt_risk.setToolTipText("");
        txt_risk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_riskFocusLost(evt);
            }
        });
        txt_risk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_riskActionPerformed(evt);
            }
        });

        lbl_risk.setText("IRCA");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Realizado por Esteban Cabarcas Henao");

        btnRegistrarEnBD.setText("Registrar en base de datos");
        btnRegistrarEnBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEnBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_city, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_water_type, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_water_type, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_risk, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_risk, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_body_type, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_body_type, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRegistrarEnBD))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_city)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_water_type)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_water_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_body_type)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_body_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_risk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_risk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarEnBD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addGap(413, 413, 413))
        );

        jTabbedPane1.addTab("Registro de datos", jPanel1);

        jPanel2.setEnabled(false);

        btnProcess.setText("Procesar");
        btnProcess.setEnabled(false);
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        lbl_inputs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_inputs.setText("Datos registrados en base de datos");

        txta_inputs.setEditable(false);
        txta_inputs.setColumns(20);
        txta_inputs.setRows(5);
        jScrollPane2.setViewportView(txta_inputs);

        txta_outputs.setEditable(false);
        txta_outputs.setColumns(20);
        txta_outputs.setRows(5);
        jScrollPane1.setViewportView(txta_outputs);

        lbl_outputs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_outputs.setText("Resultado");

        btnGetData.setText("Obtener Datos");
        btnGetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(lbl_inputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_outputs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnGetData, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_outputs)
                    .addComponent(lbl_inputs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGetData)
                    .addComponent(btnProcess))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Procesamiento de datos", jPanel2);

        txt_name1.setToolTipText("");
        txt_name1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_name1.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txt_name1.setEnabled(false);
        txt_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_name1ActionPerformed(evt);
            }
        });

        lbl_name1.setText("Nombre");

        txt_city1.setToolTipText("");
        txt_city1.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txt_city1.setEnabled(false);
        txt_city1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_city1ActionPerformed(evt);
            }
        });

        lbl_city1.setText("Municipio");

        txt_water_type1.setToolTipText("");
        txt_water_type1.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txt_water_type1.setEnabled(false);
        txt_water_type1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_water_type1ActionPerformed(evt);
            }
        });

        lbl_water_type1.setText("Tipo de agua");

        txt_id1.setToolTipText("");
        txt_id1.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txt_id1.setEnabled(false);
        txt_id1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_id1FocusLost(evt);
            }
        });
        txt_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id1ActionPerformed(evt);
            }
        });

        lbl_id1.setText("ID");

        txt_body_type1.setToolTipText("");
        txt_body_type1.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txt_body_type1.setEnabled(false);
        txt_body_type1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_body_type1ActionPerformed(evt);
            }
        });

        lbl_body_type1.setText("Tipo de cuerpo de agua");

        txt_risk1.setToolTipText("");
        txt_risk1.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txt_risk1.setEnabled(false);
        txt_risk1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_risk1FocusLost(evt);
            }
        });
        txt_risk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_risk1ActionPerformed(evt);
            }
        });

        lbl_risk1.setText("IRCA");

        lbl_id2.setText("ID");

        txt_id2.setToolTipText("");
        txt_id2.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txt_id2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_id2FocusLost(evt);
            }
        });
        txt_id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id2ActionPerformed(evt);
            }
        });

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEdit.setText("Editar");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Eliminar");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(49, 49, 49))
        );

        btnAccept.setText("Aceptar");
        btnAccept.setEnabled(false);
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lbl_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_city1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_city1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_water_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_water_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_risk1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_body_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_risk1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_body_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(142, 142, 142)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id2)
                    .addComponent(txt_id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_name1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_city1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_city1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_water_type1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_water_type1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_id1)
                                .addGap(10, 10, 10)
                                .addComponent(txt_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_body_type1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_body_type1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_risk1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_risk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAccept)
                            .addComponent(btnCancel)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar / Eliminar Datos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        txta_outputs.setText("");
        int counter = 0;
        CuerpoDeAgua vectorc[] = new CuerpoDeAgua[arrayDB.length];
        for (int i = 0; i < arrayDB.length; i++) {
                vectorc[i] = new CuerpoDeAgua();
                vectorc[i].setName(arrayDB[i][1]);
                vectorc[i].setId(Integer.parseInt(arrayDB[i][0]));
                vectorc[i].setCity(arrayDB[i][2]);
                vectorc[i].setRisk_index(Float.parseFloat(arrayDB[i][5]));                
        }

        for (CuerpoDeAgua c : vectorc) {
            txta_outputs.append("ID."+ c.getId() + " riesgo: " + c.getRisk_lvl() + ".\n");
        }
        txta_outputs.append("-----------------------------------------------------------------\n");
        for (CuerpoDeAgua c : vectorc) {
            if(c.getRisk_index()>= 0 & c.getRisk_index()<= 35){
                counter ++;
            }
        }
        txta_outputs.append("hay "+String.valueOf(counter)+ " cuerpos de agua con riesgo Medio o inferior.\n");
        txta_outputs.append("-----------------------------------------------------------------\n");
        txta_outputs.append("Nombre de cuerpos de agua con riesgo MEDIO: \n");
        counter = 0;
        for (CuerpoDeAgua c : vectorc) {
            if(c.getRisk_lvl().equals("MEDIO")){
                txta_outputs.append("* " + c.getName()+"\n");
                counter ++;
            }
        }
        if(counter == 0){
            txta_outputs.append("NA.\n");
        }
        txta_outputs.append("-----------------------------------------------------------------\n");

        counter = 0;
        for (int i = 0; i < vectorc.length; i++) {
            if(vectorc[i].getRisk_index() < vectorc[counter].getRisk_index()){
                counter = i;
            }
        }
        txta_outputs.append("El cuerpo de agua con menor riesgo es:\n");
        txta_outputs.append(vectorc[counter].getName() + ", ID: " + vectorc[counter].getId()+".\n");
        btnProcess.setEnabled(false);
        btnGetData.setEnabled(true);
        
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnGetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDataActionPerformed
        txta_inputs.setText(baseDeDatos.select("CuerposDeAgua", "ID,NOMBRE,"
                + "MUNICIPIO,TIPO_CUERPO,TIPO_AGUA,IRCA", null));
        String rows [] = new String [txta_inputs.getRows()];
        rows = txta_inputs.getText().split("\n");
        arrayDB = new String [rows.length][];
        for (int i = 0; i < arrayDB.length; i++) {
            arrayDB[i] = rows[i].split(",");
        }
        btnGetData.setEnabled(false);
        btnProcess.setEnabled(true);
    }//GEN-LAST:event_btnGetDataActionPerformed

    private void txt_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_name1ActionPerformed

    private void txt_city1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_city1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_city1ActionPerformed

    private void txt_water_type1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_water_type1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_water_type1ActionPerformed

    private void txt_id1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_id1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id1FocusLost

    private void txt_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id1ActionPerformed

    private void txt_body_type1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_body_type1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_body_type1ActionPerformed

    private void txt_risk1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_risk1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_risk1FocusLost

    private void txt_risk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_risk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_risk1ActionPerformed

    private void txt_id2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_id2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id2FocusLost

    private void txt_id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id2ActionPerformed

    private void btnRegistrarEnBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEnBDActionPerformed

        if(txt_body_type.getText().isEmpty()||txt_city.getText().isEmpty()||
            txt_id.getText().isEmpty()||txt_name.getText().isEmpty()||
            txt_risk.getText().isEmpty()||txt_water_type.getText().isEmpty()){

            JOptionPane.showMessageDialog(rootPane,
                "Faltan campos por rellenar.");
        }else{
            String data = txt_id.getText()+", '"+txt_name.getText()+"', '"+
                txt_city.getText()+"', '"+txt_body_type.getText()+"', '"+
                txt_water_type.getText()+"', '"+txt_risk.getText()+"'";
            
            if (baseDeDatos.insert("CuerposDeAgua", "ID,NOMBRE,MUNICIPIO,TIPO_CUERPO,TIPO_AGUA,IRCA", data)){
                JOptionPane.showMessageDialog(rootPane, "Registro en base de datos fue exitoso.");
            }else{
                JOptionPane.showMessageDialog(rootPane, "No se pudo realizar registro.");
            }
            
            txt_body_type.setText("");
            txt_city.setText("");
            txt_id.setText("");
            txt_name.setText("");
            txt_risk.setText("");
            txt_water_type.setText("");
            txt_name.grabFocus();
        }
    }//GEN-LAST:event_btnRegistrarEnBDActionPerformed

    private void txt_riskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_riskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_riskActionPerformed

    private void txt_riskFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_riskFocusLost
    }//GEN-LAST:event_txt_riskFocusLost

    private void txt_body_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_body_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_body_typeActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_idFocusLost
    }//GEN-LAST:event_txt_idFocusLost

    private void txt_water_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_water_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_water_typeActionPerformed

    private void txt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        id = txt_id1.getText();
        initialItemState(false);
        btnAccept.setEnabled(true);
        btnCancel.setEnabled(true);
        btnEdit.setEnabled(false);
        btnSearch.setEnabled(false);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane, "confirma la eliminación del registro con ID = "+txt_id1.getText()) == 0){
            baseDeDatos.delete("CuerposDeAgua", "ID = "+txt_id1.getText());
            JOptionPane.showMessageDialog(rootPane, "Registro con ID = " +txt_id1.getText()+" fue eliminado con éxito.");
            initialItemState(true);
            setTextFieldsEmpty();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            String result[] = new String [1];
            result = baseDeDatos.select("CuerposDeAgua", "ID,NOMBRE,MUNICIPIO,"
                    + "TIPO_CUERPO,TIPO_AGUA,IRCA", "ID = "+
                            txt_id2.getText()).split(",");
            txt_id1.setText(result[0]);
            txt_name1.setText(result[1]);
            txt_city1.setText(result[2]);
            txt_body_type1.setText(result[3]);
            txt_water_type1.setText(result[4]);
            txt_risk1.setText(result[5]);
            btnEdit.setEnabled(true);
            btnDelete.setEnabled(true);
            txt_id2.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "registro no encontrado o ID mal"
                    + " escrito, vuelva a intentarlo");
            setTextFieldsEmpty();
            initialItemState(true);
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        
        if(baseDeDatos.update("CuerposDeAgua", "ID="+txt_id1.getText()+",NOMBRE"
                + "='"+txt_name1.getText()+ "',MUNICIPIO='"+txt_city1.getText()+
                "',TIPO_CUERPO='"+txt_body_type1.getText()+"',TIPO_AGUA='"+
                txt_water_type1.getText()+"',IRCA="+txt_risk1.getText(),
                "ID="+id)){
            JOptionPane.showMessageDialog(rootPane, "Registro modificado con éxito.");
            
        }else{
        JOptionPane.showMessageDialog(rootPane, "Ya existe un registro con ese ID\nNo se realizó modificación");
        }
        initialItemState(true);
        setTextFieldsEmpty();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setTextFieldsEmpty();
        initialItemState(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void initialItemState(boolean b){
        
        txt_name1.setEnabled(!b);
        txt_city1.setEnabled(!b);
        txt_body_type1.setEnabled(!b);
        txt_risk1.setEnabled(!b);
        txt_id1.setEnabled(!b);
        txt_water_type1.setEnabled(!b);
        txt_id2.setEnabled(b);
        btnEdit.setEnabled(!b);
        btnDelete.setEnabled(!b);
        btnAccept.setEnabled(!b);
        btnCancel.setEnabled(!b);
        btnSearch.setEnabled(b);
    }
    
    private void setTextFieldsEmpty(){
            txt_name.setText("");
            txt_city.setText("");
            txt_body_type.setText("");
            txt_risk.setText("");
            txt_id.setText("");
            txt_water_type.setText("");
            txt_name1.setText("");
            txt_city1.setText("");
            txt_body_type1.setText("");
            txt_risk1.setText("");
            txt_id1.setText("");
            txt_water_type1.setText("");
            txt_id2.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnGetData;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnRegistrarEnBD;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_body_type;
    private javax.swing.JLabel lbl_body_type1;
    private javax.swing.JLabel lbl_city;
    private javax.swing.JLabel lbl_city1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_id1;
    private javax.swing.JLabel lbl_id2;
    private javax.swing.JLabel lbl_inputs;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_outputs;
    private javax.swing.JLabel lbl_risk;
    private javax.swing.JLabel lbl_risk1;
    private javax.swing.JLabel lbl_water_type;
    private javax.swing.JLabel lbl_water_type1;
    private javax.swing.JTextField txt_body_type;
    private javax.swing.JTextField txt_body_type1;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_city1;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id1;
    private javax.swing.JTextField txt_id2;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_name1;
    private javax.swing.JTextField txt_risk;
    private javax.swing.JTextField txt_risk1;
    private javax.swing.JTextField txt_water_type;
    private javax.swing.JTextField txt_water_type1;
    private javax.swing.JTextArea txta_inputs;
    private javax.swing.JTextArea txta_outputs;
    // End of variables declaration//GEN-END:variables
}
